apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps -o user,comm,args | egrep -i "^root[ ]*vsftpd.*\.conf"
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 40000
          name: pasv1
        - containerPort: 40001
          name: pasv2
        - containerPort: 40002
          name: pasv3
        - containerPort: 40003
          name: pasv4
        - containerPort: 40004
          name: pasv5
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: ftps
      port: 21
      targetPort: 21    
    - protocol: TCP
      name: pasv1
      port: 40000
      targetPort: 40000
    - protocol: TCP
      name: pasv2
      port: 40001
      targetPort: 40001
    - protocol: TCP
      name: pasv3
      port: 40002
      targetPort: 40002
    - protocol: TCP
      name: pasv4
      port: 40003
      targetPort: 40003
    - protocol: TCP
      name: pasv5
      port: 40004
      targetPort: 40004