{
 "title": "Nginx",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "select": [
      [
       { "params": [ "capacity_cpu_cores" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Capacity memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 15, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "select": [
      [
       { "params": [ "capacity_memory_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Port",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_service",
     "select": [
      [
       { "params": [ "port" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "service_name", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "Container - total restarts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_pod_container",
     "select": [
      [
       { "params": [ "restarts_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=", "value": "nginx" }
     ]
    }
   ]
  },
  {
   "title": "Allocatable memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 15, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_node",
     "select": [
      [
       { "params": [ "allocatable_memory_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kubernetes_deployment",
     "select": [
      [
       { "params": [ "replicas_available" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "deployment_name", "operator": "=", "value": "nginx-deployment" }
     ]
    }
   ]
  }
 ]
}